# Generated by Django 5.1.4 on 2026-01-31 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', '予約済'), ('completed', '達成'), ('missed', '未達成'), ('recovery', 'リカバリ')], default='scheduled', max_length=16)),
                ('checkin_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('activity_type', models.CharField(blank=True, choices=[('walk', '歩く'), ('run', '走る'), ('workout', '筋トレ'), ('other', 'その他')], max_length=16, null=True)),
                ('memo', models.TextField(blank=True, default='')),
                ('share_detail', models.BooleanField(default=False)),
                ('used_recovery', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='accounts.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
