# Generated by Django 6.0.1 on 2026-01-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tickettransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source', 'INITIAL_GRANT'), _negated=True), models.Q(('ref_type__isnull', False), ('ref_id__isnull', False)), _connector='OR'), name='initial_grant_requires_ref'),
        ),
    ]
