# Generated by Django 6.0.1 on 2026-02-02 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_tickettransaction_initial_grant_requires_ref'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelinePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('summary_only', '概要のみ'), ('with_detail', '詳細あり')], default='summary_only', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_post', to='reservations.reservation')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_posts', to='accounts.teams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
