# Generated by Django 5.1.4 on 2026-02-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS "timeline_like" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "created_at" datetime NOT NULL,
                "user_id" bigint NOT NULL REFERENCES "accounts_userprofiles" ("id") DEFERRABLE INITIALLY DEFERRED,
                "post_id" bigint NOT NULL REFERENCES "timeline_timelinepost" ("id") DEFERRABLE INITIALLY DEFERRED
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "timeline_like_user_id_post_id_uniq" ON "timeline_like" ("user_id", "post_id");
            CREATE INDEX IF NOT EXISTS "timeline_like_user_id_idx" ON "timeline_like" ("user_id");
            CREATE INDEX IF NOT EXISTS "timeline_like_post_id_idx" ON "timeline_like" ("post_id");
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS "timeline_like_post_id_idx";
            DROP INDEX IF EXISTS "timeline_like_user_id_idx";
            DROP INDEX IF EXISTS "timeline_like_user_id_post_id_uniq";
            DROP TABLE IF EXISTS "timeline_like";
            """,
        ),
    ]
